"""Add support, audit, coupon, 2FA, entitlement, payment models

Revision ID: 57a7fcdd6e8b
Revises: 
Create Date: 2026-01-16 07:28:27.788057+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic
revision = '57a7fcdd6e8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoices_id', table_name='invoices')
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.drop_index('ix_invoices_razorpay_invoice_id', table_name='invoices')
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.drop_index('ix_invoices_status_due', table_name='invoices')
    op.drop_index('ix_invoices_stripe_invoice_id', table_name='invoices')
    op.drop_index('ix_invoices_subscription_id', table_name='invoices')
    op.drop_index('ix_invoices_tenant_id', table_name='invoices')
    op.drop_index('ix_invoices_user_id', table_name='invoices')
    op.drop_index('ix_invoices_user_issued', table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=100), nullable=False),
    sa.Column('amount_due', sa.INTEGER(), nullable=False),
    sa.Column('amount_paid', sa.INTEGER(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('issued_at', sa.DATETIME(), nullable=False),
    sa.Column('due_date', sa.DATETIME(), nullable=False),
    sa.Column('paid_at', sa.DATETIME(), nullable=True),
    sa.Column('line_items', sqlite.JSON(), nullable=False),
    sa.Column('stripe_invoice_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('razorpay_invoice_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('pdf_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('hosted_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('extra_data', sqlite.JSON(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_user_issued', 'invoices', ['user_id', 'issued_at'], unique=False)
    op.create_index('ix_invoices_user_id', 'invoices', ['user_id'], unique=False)
    op.create_index('ix_invoices_tenant_id', 'invoices', ['tenant_id'], unique=False)
    op.create_index('ix_invoices_subscription_id', 'invoices', ['subscription_id'], unique=False)
    op.create_index('ix_invoices_stripe_invoice_id', 'invoices', ['stripe_invoice_id'], unique=1)
    op.create_index('ix_invoices_status_due', 'invoices', ['status', 'due_date'], unique=False)
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.create_index('ix_invoices_razorpay_invoice_id', 'invoices', ['razorpay_invoice_id'], unique=1)
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=1)
    op.create_index('ix_invoices_id', 'invoices', ['id'], unique=False)
    # ### end Alembic commands ###
